# Generated by Django 6.0.3 on 2026-03-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('general_rating', models.FloatField()),
                ('total_ratings', models.IntegerField()),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField()),
                ('tmdb_poster_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_rating', models.FloatField(null=True)),
                ('watched_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
